// File generated by Antigravity/Stitch based on manual project retrieval.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwlANvHhV8IiRD3-8KhI8n7wsuZDoJUFo',
    appId: '1:459769965590:web:9ad229369243aa470a9937',
    messagingSenderId: '459769965590',
    projectId: 'navjeevan-app-630',
    authDomain: 'navjeevan-app-630.firebaseapp.com',
    storageBucket: 'navjeevan-app-630.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgB1FRrWmMaR4TiOQ-x81rOakrmVEdtHM',
    appId: '1:459769965590:android:0c34f58ec48486f10a9937',
    messagingSenderId: '459769965590',
    projectId: 'navjeevan-app-630',
    storageBucket: 'navjeevan-app-630.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnG1cUCm82ZF0SlNIUW54BxqmSA8x-srA',
    appId: '1:459769965590:ios:8adb0f266fe088be0a9937',
    messagingSenderId: '459769965590',
    projectId: 'navjeevan-app-630',
    storageBucket: 'navjeevan-app-630.firebasestorage.app',
    iosBundleId: 'com.example.navjeevan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnG1cUCm82ZF0SlNIUW54BxqmSA8x-srA',
    appId: '1:459769965590:ios:8adb0f266fe088be0a9937',
    messagingSenderId: '459769965590',
    projectId: 'navjeevan-app-630',
    storageBucket: 'navjeevan-app-630.firebasestorage.app',
    iosBundleId: 'com.example.navjeevan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwlANvHhV8IiRD3-8KhI8n7wsuZDoJUFo',
    appId: '1:459769965590:web:b4ca1f2660c9a1d30a9937',
    messagingSenderId: '459769965590',
    projectId: 'navjeevan-app-630',
    authDomain: 'navjeevan-app-630.firebaseapp.com',
    storageBucket: 'navjeevan-app-630.firebasestorage.app',
  );

}